### ISSUE TITLE
Write and post a brief on upwork for 3d room images

### ISSUE THREAD

**Issue by shylands** [GavinShields/storestuff#31]
To go live we need these though I can find some free placeholders for now (of what I'm not sure)

----

To do this you need to sign up to http://upwork.com/ as a client and post a brief.

Example brief
----

## 3D Modeling of Interior Storage Rooms

Hello, we require a 3D designer to create a series of interior storage room images for our self-storage business. These will be used on our website and in other marketing materials.

Each image should look exactly the same style wise but will differ in the following ways:
- Each image will be of a room of different dimensions and the render should be an accurate representation of these dimensions.
- Different amount of items should be included within each room to fill its size.

The rooms should be filled with items such as cardboard boxes, picture frames, sofas, cookers, washing machines, storage cabinets, wardrobes, sets of drawers, bikes, chairs and prams. There should also be an average height man standing alongside the room for scale.

The dimensions of each room should be visible in each image. We require XX different images, one for each room size:

- 10 ft (w) 5 ft (d) 8 ft (h)
- etc

We have attached examples which are very close to our requirements and our an image of our branding for colour matching. 

The final deliverable should be high-res exported images of each room from one angle on a transparent background + the editable files.

Any questions let me know. Thanks.

**Comment by shylands** [comment]
@GavinShields updated with the first version of a brief

**Comment by shylands** [comment]
![example-large](https://user-images.githubusercontent.com/310547/61282728-23556500-a7bc-11e9-80ba-d5e0df4e4dc3.jpg)
![Uploading example-medium.jpg
![example-small](https://user-images.githubusercontent.com/310547/61282731-23556500-a7bc-11e9-9b53-d21c4a948331.jpg)
…]()

**Comment by GavinShields** [comment]
Brief posted.
